# SPDX-License-Identifier: GPL-2.0-or-later

KEY_SIZE_RATIO = 6
KEY_SPACING_RATIO = 0.5
KEY_ROUNDNESS = 0.08

KEYCODE_BTN_RATIO = 6

WINDOW_WIDTH, WINDOW_HEIGHT = 1920, 1080

KEYBOARD_WIDGET_PADDING = 5

KEYBOARD_WIDGET_MASK_HEIGHT = 0.65
KEYBOARD_WIDGET_NONMASK_PADDING = 0.02

SHADOW_SIDE_PADDING = 0.1
SHADOW_TOP_PADDING = 0.05
SHADOW_BOTTOM_PADDING = 0.15
